### ISSUE TITLE
Problems running sbom4python on Windows

### ISSUE THREAD

**Issue by tngraf** [anthonyharrison/sbom4python#11]
Hi Anthony,

I tried to run sbom4python on Windows. The result was
```
PS E:\Software\Python\sbom4python> sbom4python -m capycli --sbom cyclonedx --format json -o sbom_AH.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\sbom4python.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\sbom4python\cli.py", line 14, in <module>
    from sbom4python.scanner import SBOMScanner
  File "C:\Program Files\Python311\Lib\site-packages\sbom4python\scanner.py", line 12, in <module>
    from sbom4files.filescanner import FileScanner
  File "C:\Program Files\Python311\Lib\site-packages\sbom4files\filescanner.py", line 7, in <module>
    import magic
  File "C:\Program Files\Python311\Lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

I assume all libraries have been installed:
```
pip list
Package                  Version     Editable project location
------------------------ ----------- ----------------------------------------
aiofiles                 22.1.0
aiosqlite                0.18.0
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.1.0
Babel                    2.12.1
backcall                 0.2.0
beautifulsoup4           4.11.2
binaryornot              0.4.4
black                    23.3.0
bleach                   5.0.1
BomConverter             0.1         E:\Siemens\Software\Python\bom-converter
boolean.py               4.0
certifi                  2022.12.7
cffi                     1.15.1
chardet                  5.1.0
charset-normalizer       2.1.1
click                    8.1.3
colorama                 0.4.6
comm                     0.1.2
commonmark               0.9.1
contourpy                1.0.7
cycler                   0.11.0
cyclonedx-bom            3.11.0
cyclonedx-python-lib     3.1.5
dateparser               1.1.7
debugpy                  1.6.6
decorator                5.1.1
defusedxml               0.7.1
docutils                 0.19
et-xmlfile               1.1.0
executing                1.2.0
fastjsonschema           2.16.3
filelock                 3.11.0
flake8                   5.0.4
fonttools                4.39.0
fqdn                     1.5.1
idna                     3.4
importlib-metadata       5.2.0
ipykernel                6.21.3
ipython                  8.11.0
ipython-genutils         0.2.0
isoduration              20.11.0
isort                    5.12.0
jaraco.classes           3.2.3
jedi                     0.18.2
Jinja2                   3.1.2
json5                    0.9.11
jsonpointer              2.3
jsonschema               4.17.3
jupyter_client           8.0.3
jupyter_core             5.2.0
jupyter-events           0.6.3
jupyter_server           2.4.0
jupyter_server_fileid    0.8.0
jupyter_server_terminals 0.4.4
jupyter_server_ydoc      0.6.1
jupyter-ydoc             0.2.3
jupyterlab               3.6.1
jupyterlab-pygments      0.2.2
jupyterlab_server        2.20.0
keyring                  23.13.1
kiwisolver               1.4.4
lib4sbom                 0.4.0
license-expression       30.1.0
MarkupSafe               2.1.2
matplotlib               3.7.1
matplotlib-inline        0.1.6
mccabe                   0.7.0
mistune                  2.0.5
more-itertools           9.0.0
mpmath                   1.3.0
mypy                     1.3.0
mypy-extensions          1.0.0
nbclassic                0.5.3
nbclient                 0.7.2
nbconvert                7.2.9
nbformat                 5.7.3
nest-asyncio             1.5.6
networkx                 3.1
notebook                 6.5.3
notebook_shim            0.2.2
numdifftools             0.9.41
numpy                    1.24.2
openpyxl                 3.1.2
packageurl-python        0.10.4
packaging                23.0
pandas                   1.5.3
pandocfilters            1.5.0
parso                    0.8.3
pathspec                 0.11.1
pickleshare              0.7.5
Pillow                   9.4.0
pip                      22.3.1
pip-requirements-parser  32.0.1
pkginfo                  1.9.2
platformdirs             3.1.1
prometheus-client        0.16.0
prompt-toolkit           3.0.38
psutil                   5.9.4
pure-eval                0.2.2
pycodestyle              2.9.1
pycparser                2.21
pyflakes                 2.5.0
Pygments                 2.13.0
pyparsing                3.0.9
pyrsistent               0.19.2
pyrsistent               0.19.2
python-dateutil          2.8.2
python-debian            0.1.49
python-json-logger       2.0.7
python-magic             0.4.27
python-magic-bin         0.4.14
pytz                     2022.7.1
pytz-deprecation-shim    0.1.0.post0
pywin32                  305
pywin32-ctypes           0.2.0
pywinpty                 2.0.10
PyYAML                   6.0
pyzmq                    25.0.0
readme-renderer          37.3
regex                    2022.10.31
regex                    2022.10.31
requests                 2.28.1
requests-toolbelt        0.10.1
reuse                    1.1.2
rfc3339-validator        0.1.4
rfc3986                  2.0.0
rfc3986-validator        0.1.1
rich                     12.6.0
sbom2dot                 0.3.0
sbom4files               0.3.0
sbom4python              0.10.0
scipy                    1.10.1
semantic-version         2.10.0
Send2Trash               1.8.0
setuptools               67.6.0
six                      1.16.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.4
stack-data               0.6.2
standard-bom-validator   0.1
StandardBomValidator     0.1
sympy                    1.11.1
terminado                0.17.1
tinycss2                 1.2.1
toml                     0.10.2
toml                     0.10.2
tomli                    2.0.1
torch                    2.0.0
tornado                  6.2
traitlets                5.9.0
twine                    4.0.2
types-colorama           0.4.15.12
typing_extensions        4.5.0
tzdata                   2022.7
tzdata                   2022.7
tzlocal                  4.2
tzlocal                  4.2
uri-template             1.2.0
urllib3                  1.26.13
wcwidth                  0.2.6
webcolors                1.12
webencodings             0.5.1
websocket-client         1.5.1
wheel                    0.34.2
y-py                     0.5.9
ypy-websocket            0.8.2
zipp                     3.11.0
```

I am running Python 3.11.0 on Windows 10.

**Comment by anthonyharrison** [comment]
Hello @tngraf . 

I am aware that the magic library is problematic on Windows (The problem is related to this issue https://github.com/anthonyharrison/sbom4files/issues/2 . )

As a temporary workaround can you try removing python-magic 

`pip uninstall pyhton-magic`

and see if that works.
