### ISSUE TITLE
failed to use this tool to generate SBOM from utf-8 files

### ISSUE THREAD

**Issue by swiftt112** [anthonyharrison/sbom4python#12]
Thank you four your work, but I encountered the following error when using SBOM to generate files, could you please give me some advice? The logs are as followed:
D:\tool\software\anaconda\envs\KNsbom\Scripts>sbom4python -m D:\the_code\python --sbom spdx --format json -o D:\the_code\STM32project\2-1STM32-22112801\output_sbom.json
Traceback (most recent call last):
  File "D:\tool\software\anaconda\envs\KNsbom\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\tool\software\anaconda\envs\KNsbom\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\tool\software\anaconda\envs\KNsbom\Scripts\sbom4python.exe\__main__.py", line 7, in <module>
  File "D:\tool\software\anaconda\envs\KNsbom\lib\site-packages\sbom4python\cli.py", line 131, in main
    sbom_scan = SBOMScanner(
  File "D:\tool\software\anaconda\envs\KNsbom\lib\site-packages\sbom4python\scanner.py", line 27, in __init__
    self.sbom_package = SBOMPackage()
  File "D:\tool\software\anaconda\envs\KNsbom\lib\site-packages\lib4sbom\data\package.py", line 13, in __init__
    self.license = LicenseScanner()
  File "D:\tool\software\anaconda\envs\KNsbom\lib\site-packages\lib4sbom\license.py", line 18, in __init__
    self.licenses = json.load(licfile)
  File "D:\tool\software\anaconda\envs\KNsbom\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 87462: illegal multibyte sequence

It seems this the work has voked in dealing with files coding not in 'gbk'. I doubt if i use the wrong command, the command is as followed:
sbom4python -m D:\the_code\python --sbom spdx --format json -o D:\the_code\STM32project\2-1STM32-22112801\output_sbom.json

Could you please give me some advice? Thank you very much.

**Comment by anthonyharrison** [comment]
@swiftt112 Thanks for the report.

I will have to see if I can reproduce it but it looks as if you are running on Windows with an anaconda distribution, neither of which I have readily available!

The error relates to the loading of a data file used by the SBOM generator. I have checked that the file does not contain any non-utf-8 characters on my Linux machine. However, having looked at the code, I think explicitly stating that the encoding is utf-8  might be an improvement.

Can you confirm that running the code in a clean Python virtual environment (which version of Python are you using?), makes no difference?

**Comment by anthonyharrison** [comment]
@swiftt112 This is fixed with an update to lib4sbom (version 0.6.2). Reinstall/upgrade lib4sbom and it should work.
