### ISSUE TITLE
sbom4python 0.12.0 on Python 3.12 is missing toml

### ISSUE THREAD

**Issue by LordGaav** [anthonyharrison/sbom4python#27]
Running the latest version Python 3.12 results in a missing dependency on toml. Looking at the requirements.txt, toml is only installed on Python < 3.11. However, the toml library in Python 3.12 is called `tomllib`.

See the stack trace below running on a clean docker image for Python 3.12:

```
root@574ea9f8a4ac:/# pip install sbom4python
Collecting sbom4python
  Downloading sbom4python-0.12.0-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting lib4package>=0.3.0 (from sbom4python)
  Downloading lib4package-0.3.1-py2.py3-none-any.whl.metadata (6.3 kB)
Collecting lib4sbom>=0.8.0 (from sbom4python)
  Downloading lib4sbom-0.8.0-py2.py3-none-any.whl.metadata (42 kB)
Collecting sbom2dot>=0.3.0 (from sbom4python)
  Downloading sbom2dot-0.3.1-py2.py3-none-any.whl.metadata (7.9 kB)
Collecting sbom4files>=0.4.4 (from sbom4python)
  Downloading sbom4files-0.4.5-py2.py3-none-any.whl.metadata (6.3 kB)
Collecting requests (from lib4package>=0.3.0->sbom4python)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyyaml>=5.4 (from lib4sbom>=0.8.0->sbom4python)
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting semantic-version (from lib4sbom>=0.8.0->sbom4python)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting defusedxml (from lib4sbom>=0.8.0->sbom4python)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting python-magic (from sbom4files>=0.4.4->sbom4python)
  Downloading python_magic-0.4.27-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting charset-normalizer<4,>=2 (from requests->lib4package>=0.3.0->sbom4python)
  Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->lib4package>=0.3.0->sbom4python)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->lib4package>=0.3.0->sbom4python)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->lib4package>=0.3.0->sbom4python)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading sbom4python-0.12.0-py2.py3-none-any.whl (45 kB)
Downloading lib4package-0.3.1-py2.py3-none-any.whl (10 kB)
Downloading lib4sbom-0.8.0-py2.py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 20.6 MB/s eta 0:00:00
Downloading sbom2dot-0.3.1-py2.py3-none-any.whl (6.4 kB)
Downloading sbom4files-0.4.5-py2.py3-none-any.whl (12 kB)
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 15.5 MB/s eta 0:00:00
Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Downloading python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (143 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: urllib3, semantic-version, pyyaml, python-magic, idna, defusedxml, charset-normalizer, certifi, requests, lib4sbom, sbom4files, sbom2dot, lib4package, sbom4python
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 defusedxml-0.7.1 idna-3.10 lib4package-0.3.1 lib4sbom-0.8.0 python-magic-0.4.27 pyyaml-6.0.2 requests-2.32.3 sbom2dot-0.3.1 sbom4files-0.4.5 sbom4python-0.12.0 semantic-version-2.10.0 urllib3-2.2.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@574ea9f8a4ac:/# sbom4python -h
Traceback (most recent call last):
  File "/usr/local/bin/sbom4python", line 5, in <module>
    from sbom4python.cli import main
  File "/usr/local/lib/python3.12/site-packages/sbom4python/cli.py", line 14, in <module>
    from sbom4python.scanner import SBOMScanner
  File "/usr/local/lib/python3.12/site-packages/sbom4python/scanner.py", line 14, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

**Comment by anthonyharrison** [comment]
Thanks for spotting this.
